version: '3.5'

services:
    mariadb:
        build: ./requirements/mariadb/
        volumes:
        - database:/var/lib/mysql
        env_file:
        - .env
        restart: always
        networks:
        - backend
        stdin_open: true
        tty: true
    wordpress:
        depends_on:
        - mariadb
        build: ./requirements/wordpress/
        volumes:
        - wordpress:/var/www/html
        env_file:
        - .env
        restart: always
        networks:
        - backend
        stdin_open: true
        tty: true
    nginx:
        build: ./requirements/nginx/
        volumes:
        - wordpress:/var/www/html
        env_file:
        - .env
        ports:
        - "8080:80"
        restart: always
        networks:
        - backend
        stdin_open: true
        tty: true

networks:
  backend:
    driver: bridge

volumes:
  database:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/rotrojan/data/database"
  wordpress:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/rotrojan/data/wordpress"
