---
version: '3.8'

services:
    mariadb:
        build: ./requirements/mariadb/
        volumes:
          - database:/var/lib/mysql
        env_file:
          - .env
        ports:
          - "3306:3306"
        restart: on-failure
        networks:
          - backend
        stdin_open: true
        tty: true
    wordpress:
        depends_on:
          - mariadb
        build: ./requirements/wordpress/
        volumes:
          - wordpress:/var/www/html/localhost
        env_file:
          - .env
        restart: on-failure
        networks:
          - backend
        stdin_open: true
        tty: true
    nginx:
        depends_on:
          - wordpress
        build: ./requirements/nginx/
        volumes:
          - wordpress:/var/www/html/localhost
        env_file:
          - .env
        ports:
          - "8080:80"
        restart: on-failure
        networks:
          - backend
        links:
          - wordpress
        stdin_open: true
        tty: true

networks:
  backend:
    driver: bridge

volumes:
  database:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/data/mysql"
  wordpress:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/data/html"
