version: '3'

services:
    mysql:
        build: ./requirements/mariadb/
        volumes:
        - /data/mysql:/var/lib/mysql
        env_file:
        - .env
        restart: always
        networks:
          - backend
    wordpress:
        depends_on:
        - mysql
        build: ./requirements/wordpress/
        volumes:
        - /data/html:/var/www/html
        env_file:
        - .env
        restart: always
        networks:
        - backend
    nginx:
        build: ./requirements/nginx/
        volumes:
        - nginx:/etc/nginx/conf.d
        - /data/html:/var/www/html
        ports:
        - "8080:80"
        restart: always
        networks:
        - backend

networks:
  backend:
    driver: bridge

volumes:
  nginx:
