#!/usr/bin/env sh

#service mysql start
#mysql -u root << EOF
#CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE;
#USE $MYSQL_DATABASE;
#CREATE USER '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';
#GRANT ALL PRIVILEGES ON $MYSQL_DATABASE TO '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';
#FLUSH PRIVILEGES;
#EOF

[ "$DEBUG" = 1 ] && exec /bin/bash || exec "$@"
